package com.epam.service.api.exception;

/**
 * Created by infinity on 23.02.16.
 */
public enum  ServiceStatusCode {

    AUTHOR_ALREADY_EXIST, AUTHOR_NOT_FOUND, AUTHOR_ASSIGNED,
    BOOK_NOT_FOUND, BOOK_COUNT, BOOK_ALREADY_EXIST, BOOK_ASSIGNED,
    GENRE_ALREADY_EXIST, GENRE_NOT_FOUND, GENRE_ASSIGNED,
    USER_NOT_FOUND, USER_ALREADY_EXIST,
    STATUS_NOT_FOUND,
    BOOK_ORDER_NOT_FOUND, BOOK_ORDER_ALREADY_EXIST,
    UNKNOWN

}
